#!/usr/bin/env bash
#
# sonar-audit.sh — report SonarCloud issues and unreviewed hotspots on a branch.
#
# Queries the SonarCloud API for unresolved issues and TO_REVIEW security
# hotspots on the given branch (default: main) and prints a summary. Because
# SonarCloud's free plan has no custom quality gate, this is how overall-code
# drift on a long-lived branch gets noticed: CI runs it after each scan and,
# when anything is found, fails the job and opens/refreshes a single tracking
# GitHub issue.
#
# Usage:
#   SONAR_TOKEN=... sonar-audit.sh [--branch main] [--project KEY] [--report-only]
#
#   --branch NAME   Branch to audit (default: main).
#   --project KEY   SonarCloud project key. Defaults to sonar.projectKey read
#                   from sonar-project.properties in the current directory.
#   --report-only   Print the report and exit 0 without touching GitHub issues
#                   or failing on drift (default when GH_TOKEN is unset, e.g.
#                   local runs). CI omits it to get the fail + tracking issue.
#
# Environment:
#   SONAR_TOKEN   SonarCloud token (required).
#   GH_TOKEN      GitHub token with `issues: write` (required unless --report-only).
#   SONAR_HOST    SonarCloud base URL (default: https://sonarcloud.io).
#
# Exit status: 0 when the branch is clean (or --report-only); 1 when it has any
# open issue or unreviewed hotspot; 2 on a usage error.

set -euo pipefail

HOST="${SONAR_HOST:-https://sonarcloud.io}"
PROPERTIES_FILE="sonar-project.properties"
branch="main"
project=""
report_only=0

usage() {
  sed -n '3,28p' "$0" | sed 's/^# \{0,1\}//'
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --branch) branch="$2"; shift 2 ;;
    --project) project="$2"; shift 2 ;;
    --report-only) report_only=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

if [[ -z "$project" ]]; then
  if [[ -f "$PROPERTIES_FILE" ]]; then
    project="$(sed -n 's/^[[:space:]]*sonar\.projectKey[[:space:]]*=[[:space:]]*//p' "$PROPERTIES_FILE" | head -n 1)"
  fi
fi
[[ -n "$project" ]] || {
  echo "no project key: pass --project KEY or set sonar.projectKey in $PROPERTIES_FILE" >&2
  exit 2
}

# Both values reach API query strings, a jq program, and a GitHub issue title;
# a strict charset keeps injection out of all three.
for v in "$branch" "$project"; do
  [[ "$v" =~ ^[A-Za-z0-9._:/-]+$ ]] || {
    echo "invalid characters in branch/project: $v" >&2
    exit 2
  }
done

ISSUE_TITLE="SonarCloud drift on $branch"

: "${SONAR_TOKEN:?SONAR_TOKEN is required}"
[[ -n "${GH_TOKEN:-}" ]] || report_only=1

sonar_get() {
  # -G + --data-urlencode builds the query safely; the auth header is read from
  # a process substitution so the token never appears on curl's argv (ps-visible).
  local path="$1"
  shift
  local params=()
  local q
  for q in "$@"; do
    params+=(--data-urlencode "$q")
  done
  curl -sSf -G "${params[@]}" \
    -H @<(printf 'Authorization: Bearer %s\n' "$SONAR_TOKEN") "$HOST/$path"
}

# strip the "projectKey:" prefix from a component to leave the file path
strip_component='sub("^[^:]*:"; "")'

issues_json="$(sonar_get api/issues/search "componentKeys=$project" "branch=$branch" "resolved=false" "ps=100")"
hotspots_json="$(sonar_get api/hotspots/search "projectKey=$project" "branch=$branch" "status=TO_REVIEW" "ps=100")"

issue_count="$(jq -r '.total' <<<"$issues_json")"
hotspot_count="$(jq -r '.paging.total' <<<"$hotspots_json")"
total=$((issue_count + hotspot_count))

issue_lines="$(jq -r ".issues[] | \"- **\(.severity)** \(.rule) — \(.component | $strip_component):\(.line // .textRange.startLine // \"?\") — \(.message)\"" <<<"$issues_json")"
hotspot_lines="$(jq -r ".hotspots[] | \"- **HOTSPOT** \(.ruleKey) — \(.component | $strip_component):\(.line) — \(.message)\"" <<<"$hotspots_json")"

body="$(cat <<EOF
SonarCloud analysis of \`$branch\` reports **$issue_count open issue(s)** and **$hotspot_count unreviewed hotspot(s)**.

$issue_lines
$hotspot_lines

Review at $HOST/project/issues?id=$project&resolved=false&branch=$branch

Ask Claude to "fix the sonar drift" for a scoped pass, or mark false positives / safe hotspots in SonarCloud. This issue closes automatically once the branch is clean.

Fixing this drift is tracked in the project's task tracker, not here: file an item for the round, then close it with what was fixed, what was accepted and why, and the PR number. This issue is transient.

_Generated by sonar-audit.sh._
EOF
)"

echo "branch=$branch open_issues=$issue_count unreviewed_hotspots=$hotspot_count"
echo "$issue_lines"
echo "$hotspot_lines"

if [[ "$report_only" -eq 1 ]]; then
  exit 0
fi

# Exact title match — `--search in:title` is a phrase search, which both matches
# superstring titles ("... on main-v2") and would let quotes in the phrase inject
# search qualifiers. $ISSUE_TITLE is charset-safe to embed (validated above).
existing="$(gh issue list --state open --json number,title \
  --jq ".[] | select(.title == \"$ISSUE_TITLE\") | .number" 2>/dev/null | head -n 1 || true)"

if [[ "$total" -eq 0 ]]; then
  if [[ -n "$existing" ]]; then
    gh issue close "$existing" --comment "SonarCloud reports no open issues or unreviewed hotspots on \`$branch\`. Closing."
  fi
  echo "clean"
  exit 0
fi

if [[ -n "$existing" ]]; then
  gh issue edit "$existing" --body "$body"
  echo "updated tracking issue #$existing"
else
  gh issue create --title "$ISSUE_TITLE" --body "$body"
  echo "opened tracking issue"
fi

exit 1
